TRAIN:
  ENABLE: True
  DATASET: VIDOR
  BATCH_SIZE: 128
  EVAL_PERIOD: 1
  CHECKPOINT_PERIOD: 1
  AUTO_RESUME: True
  # CHECKPOINT_FILE_PATH: path to the pretrain checkpoint file.
  CHECKPOINT_TYPE: caffe2
DATA:
  NUM_FRAMES: 32
  SAMPLING_RATE: 2
  TRAIN_JITTER_SCALES: [256, 320]
  TRAIN_CROP_SIZE: 224
  TEST_CROP_SIZE: 224
  INPUT_CHANNEL_NUM: [3, 3]
DETECTION:
  ENABLE: True
  ENABLE_HOI: True
  ALIGNED: True
VIDOR:
  DETECTION_SCORE_THRESH: 0.0
  TRAIN_GT_BOX_LISTS: ['train_frame_annots.json'] # use only gt
  TRAIN_PREDICT_BOX_LISTS: [
    # "ava_train_v2.2.csv",
    # "person_box_67091280_iou90/ava_detection_train_boxes_and_labels_include_negative_v2.2.csv",
  ]
  TEST_WITH_GT: True
  TEST_GT_BOX_LISTS: ['val_frame_annots.json'] # use gt for now
  TEST_PREDICT_BOX_LISTS: ['val_instances_predictions_train_small_vidor_with_pseudo_labels.pth'] # ['val_frame_annots.json'] # use gt for now
  # TEST_DEBUG: False # FOR DEBUG PURPOSE -> set via command line please!
SLOWFAST:
  ALPHA: 4
  BETA_INV: 8
  FUSION_CONV_CHANNEL_RATIO: 2
  FUSION_KERNEL_SZ: 7
RESNET:
  SCRATCH: True # train resnet from scratch
  ZERO_INIT_FINAL_BN: True
  WIDTH_PER_GROUP: 64
  NUM_GROUPS: 1
  DEPTH: 50
  TRANS_FUNC: bottleneck_transform
  STRIDE_1X1: False
  NUM_BLOCK_TEMP_KERNEL: [[3, 3], [4, 4], [6, 6], [3, 3]]
  SPATIAL_DILATIONS: [[1, 1], [1, 1], [1, 1], [2, 2]]
  SPATIAL_STRIDES: [[1, 1], [2, 2], [2, 2], [1, 1]]
NONLOCAL:
  LOCATION: [[[], []], [[], []], [[], []], [[], []]]
  GROUP: [[1, 1], [1, 1], [1, 1], [1, 1]]
  INSTANTIATION: dot_product
  POOL: [[[1, 2, 2], [1, 2, 2]], [[1, 2, 2], [1, 2, 2]], [[1, 2, 2], [1, 2, 2]], [[1, 2, 2], [1, 2, 2]]]
BN:
  USE_PRECISE_STATS: False
  NUM_BATCHES_PRECISE: 200
SOLVER:
  BASE_LR: 0.01
  LR_POLICY: steps_with_relative_lrs
  STEPS: [0, 10, 15, 20]
  LRS: [1, 0.1, 0.01, 0.001]
  MAX_EPOCH: 20
  MOMENTUM: 0.9
  WEIGHT_DECAY: 1e-7
  WARMUP_EPOCHS: 5.0
  WARMUP_START_LR: 0.000125
  OPTIMIZING_METHOD: sgd
MODEL:
  NUM_CLASSES: 50 # VidOR action number
  ARCH: slowfast
  MODEL_NAME: SlowFast
  LOSS_FUNC: bce
  DROPOUT_RATE: 0.5
  HEAD_ACT: sigmoid
  HOI_ON: True
  HOI_BOX_HEAD:
    NAME: "HOIRCNNConvFCHead"
    NUM_FC: 2
    POOLER_RESOLUTION: 7
    POOLER_SAMPLING_RATIO: 0
    ACTION_CLS_WEIGHTS: [10., 128.]
    ALLOW_PERSON_TO_PERSON: True
    IN_CHANNELS: 2304 # 2048 (slow) + 256 (fast) = 2304
  USE_TRAJECTORIES: True
  USE_RELATIVITY_FEAT: True # NOTE: USE_TRAJECTORIES MUST BE TRUE TOO!
TEST:
  ENABLE: True
  DATASET: VIDOR
  BATCH_SIZE: 128
DATA_LOADER:
  NUM_WORKERS: 2
  PIN_MEMORY: True
NUM_GPUS: 8
NUM_SHARDS: 1
RNG_SEED: 0
OUTPUT_DIR: ./output/SLOWFAST_32x2_R50_SHORT_SCRATCH_EVAL_GT_relativity-feat
TENSORBOARD:
  ENABLE: True
  LOG_DIR: SLOWFAST_32x2_R50_SHORT_SCRATCH_EVAL_GT_relativity-feat